name: node
description: "node setup/dependencies"
runs:
  using: "composite"
  steps:
    - name: Node setup
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 20

    - name: caching
      id: cache_dependencies
      uses: actions/cache@v4.0.1
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('package-lock.json') }}

    - name: dependencies
      shell: bash
      if: steps.cache_dependencies.outputs.cache-hit != 'true'
      run: npm ci