name: publish-github-page
on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: node setup
        uses: ./.github/workflows/node

      - name: configure pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next

      - name: build next.js
        run: npx next build

      - name: upload-pages-artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v4